### ISSUE TITLE
Issue with r40-x86 version

### ISSUE THREAD

**Issue by TbtBI** [magiblot/gradation#1]
Hi, the [x86 version](https://github.com/magiblot/gradation/releases/tag/r40) causes immediately crash. Avs+ r3667 is used.

**Comment by magiblot** [comment]
Sorry, I messed up the call convention. This should be fixed in [r50](https://github.com/magiblot/gradation/releases/tag/r50).

Cheers!

**Comment by TbtBI** [comment]
Yes, it's fixed.

Thanks.
