### ISSUE TITLE
Green Channel problem in VirtualDub 32 bit 

### ISSUE THREAD

**Issue by Gomzumi** [magiblot/gradation#2]
In Graduation Curves, the green color channel does not work in VirtualDub2 32 bit.

You can see the error in the preview window.

**Comment by magiblot** [comment]
Hi zettimetti!

What version of the plugin are you using?
Can you please share a screenshot?

Cheers.

**Comment by Gomzumi** [comment]
I using version r50

The frame i have tested with should give wierd colors with the curve you can see in the screenshot, but all colors are normal and untouched. 
https://i.ibb.co/1JNt2M6/Screenshot-2022-05-15-134017.png

**Comment by magiblot** [comment]
Okay, I have found it. Thanks for the report.

The [latest release](https://github.com/magiblot/gradation/releases/tag/r51) contains the fix.

Cheers!
