### ISSUE TITLE
Would it be possible to process floats also with rgb and full mode?

### ISSUE THREAD

**Issue by erazortt** [magiblot/gradation#3]
Would it be possible to process floats also with rgb and full mode?

**Comment by magiblot** [comment]
Yes @erazortt, the point is that I hadn't added it because I hadn't needed it yet. Are you in a hurry?

**Comment by magiblot** [comment]
If all you need are the `"rgb"` and `"full"` modes, they are now available in the [latest release](https://github.com/magiblot/gradation/releases/tag/r74).
